// Copyright (c) 2023-2026 ktsu-dev contributors

namespace ktsu.ProjectDirector.UITests.Gallery;

using System.Text;

/// <summary>Writes the gallery's <c>README.md</c>, which captions each picture.</summary>
internal static class GalleryIndex
{
	/// <summary>Renders the index for the given entries, in catalog order.</summary>
	/// <param name="entries">The entries to caption.</param>
	/// <returns>The index's text, with LF line endings.</returns>
	internal static string Render(IReadOnlyList<GalleryEntry> entries)
	{
		StringBuilder text = new();
		text.Append("# App gallery\n\n");
		text.Append("<!-- Generated by tests/ProjectDirector.UITests/Gallery. Edit GalleryCatalog.cs, not this file. -->\n\n");
		text.Append("Project Director as it draws today, staged and photographed headlessly by the UI test harness ");
		text.Append("over three small repositories seeded for the purpose. ");
		text.Append("The pictures are regenerated on every successful build of `main`, so they show the current application. ");
		text.Append("The log panel along the bottom of the window is left out of every picture, because it stamps each line with the time it was written.\n\n");

		foreach (GalleryEntry entry in entries)
		{
			text.Append("## ").Append(entry.Name).Append("\n\n");
			text.Append(entry.Description).Append("\n\n");
			text.Append("![").Append(entry.Name).Append("](").Append(entry.Slug).Append(".png)\n\n");
		}

		return text.ToString();
	}
}
